### PR TITLE
Update README.md to provide more examples

### PR DESCRIPTION
**Pull request by jamesmstone**
Partially helps zabouth/PHPMoves#3

### CODE REVIEW

**Comment by zabouth** [comment]
Hey,

You seem to have taken an interest in this project. Since I am no longer actively maintaining this code so I would be happy to add you as a collaborator to the repository if you want to keep updating it in the future

**Comment by jamesmstone** [comment]
Hey @zabouth  
As I'm currently using this library in a project, it is definitely in my best interests to keep this up to date. 
So I'd happily be made a collaborator and do my best to keep it up to date

**Comment by zabouth** [comment]
Hey @jamesmstone 
I've added you to the Collaborators list for the project you should now have push access to the repository

**Comment by jamesmstone** [comment]
Thanks

**Pull request merged**
